export const constHomePage = 
{   
    ID: {
        textHome1 : "Payment Gateway Indonesia Terlengkap untuk Bisnis Anda",
        textHome2 : "Bersama tuntaz fokus pada bisnis Anda untuk kelola semua pembayaran (disbursement) dan kirim dana dengan mudah.",
        buttonTextHome2: "Bergabung",
        weBelieve: "Kami Yakin",
        weBelieveDesc: "Dapat Membantu perusahaan anda menjadi lebih baik secara mandiri dengan mudah diikuti dan harga yang terjangkau",
        productTitle: "Produk Kami",
        productDesc: "(ID) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        acceptPayments: "Multi Pembayaran",
        acceptPaymentsDesc: "(ID) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        disburstment: "Disbursment",
        disburstmentDesc: "(ID) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        paymentLink: "Jaringan Pembayaran",
        paymentLinkDesc: "(ID) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        payments: "Payments",
        paymentsShortDesc: "Menerima beragam metode pembayaran dengan mudah",
        paymentsLongDesc: "Kenali dan terima pembayaran dari berbagai bank secara otomatis dengan satu Virtual Account dari Tuntaz, tanpa harus memiliki banyak rekening.",
        disburse: "Disburse",
        disburseShortDesc: "Kirim uang ke rekening bank, e-Wallet dan kartu Kredit 24/7",
        disburseLongDesc: "Kirim sampai dengan 10,000 transaksi dengan sekali mengunggah file excel. Tersedia sepanjang tahun, bahkan di hari libur.",
        batch: "Batch",
        batchShortDesc: "Transfer uang dengan mudah dan instan dengan menggunggah file Excel",
        batchLongDesc: "Kirim sampai dengan 10,000 transaksi dengan sekali mengunggah file excel. Tersedia sepanjang tahun, bahkan di hari libur.",
        invoice: "Invoice",
        invoiceShortDesc: "Menerima beragam metode pembayaran dengan sangat mudah",
        invoiceLongDesc: "Kami menyediakan antarmuka yang mudah dan sederhana untuk menagih pelanggan, sekaligus memberikan beragam opsi pembayaran yang diinginkan pelanggan untuk meningkatkan penjualan Anda.",
        testimoniTitle: "Apa Kata pengguna Tuntaz",
        testimoniSubTitle: "Kata pengguna",
    },
    EN: {
        textHome1 : "Indonesia's Most Complete Payment Gateway for Your Business",
        textHome2 : "With tuntaz, focus on your business to manage all payments (disbursement) and send funds easily.",
        buttonTextHome2: "Join Us",
        weBelieve: "We Believe",
        weBelieveDesc: "In Helping company become a better version of themselves with easy to follow and affordable life coaching sessions",
        productTitle: "Product",
        productDesc: "(EN) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        acceptPayments: "Accept Payment",
        acceptPaymentsDesc: "(EN) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        disburstment: "Disbursment",
        disburstmentDesc: "(EN) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        paymentLink: "Payment Link",
        paymentLinkDesc: "(EN) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec elit sed ante dictum eleifend hendrerit vitae risus",
        payments: "Payments",
        paymentsShortDesc: "Accept various payment methods easily",
        paymentsLongDesc: "Automatically recognize and receive payments from various banks with one Virtual Account from Tuntaz, without having to have multiple accounts.",
        disburse: "Disburse",
        disburseShortDesc: "Send money to bank accounts, e-Wallets and Credit cards 24/7",
        disburseLongDesc: "Send up to 10,000 transactions with one excel file upload. Available all year round, even on holidays.",
        batch: "Batch",
        batchShortDesc: "Transfer money easily and instantly by uploading an Excel file",
        batchLongDesc: "Send up to 10,000 transactions with one excel file upload. Available all year round, even on holidays.",
        invoice: "Invoice",
        invoiceShortDesc: "Accept various payment methods very easily",
        invoiceLongDesc: "We provide an easy and simple interface for billing customers, while providing a variety of payment options that customers want to increase your sales.",
        testimoniTitle: "What Tuntaz users say",
        testimoniSubTitle: "User said",
    }
}