export const constProduct = 
{   
    ID: {
        textHome1 : "Terima dan kirim pembayaran dengan mudah",
        textHome2 : "Tuntaz adalah payment gateway yang membantu bisnis Anda berkembang. Kami membantu bisnis menerima berbagai metode pembayaran dan mengirim dana ke berbagai tujuan, sehingga Anda bisa fokus pada pertumbuhan bisnis.",
        acceptPayment: 'Multi Pembayaran',
        disbursment: 'Disbursment',
        paymentLink: 'Jaringan Pembayaran',
        benefitTitle: 'Benefit untuk anda',
        benefit1Title: 'Operasi bisnis yang efisien',
        benefit1Text: 'Pantau dan atur transaksi dari dashboard kami yang dapat diakses dari beberapa perangkat sekaligus dan hasilkan laporan dengan mudah.',
        benefit2Title: 'Notifikasi secara real time',
        benefit2Text: 'Kenali, analisa dan terima pembayaran secara real time dan otomatis.',
        benefit3Title: 'Pelaporan dan analitik',
        benefit3Text: 'Gunakan dashboard berbasis web kami untuk mengakses dan mengunduh laporan keuangan yang sangat mendetil, hingga baris per baris dari rekonsiliasi seluruh transaksi untuk transparansi.',
        
        tab1Title1: 'Kompatibel dengan berbagai metode pembayaran',
        tab1Text1: 'Perluas cakupan bisnis Anda ke seluruh penjuru Indonesia dan Asia Tenggara dengan jaringan luas kami dan kemitraan dengan lebih dari 140 bank lokal. Terima notifikasi secara langsung ketika pembayaran berhasil. Lakukan rekonsiliasi dan refund yang mudah melalui dashboard Xendit.',
        tab1SubTitle1: 'Virtual Akun',
        tab1SubText1: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
        tab1SubTitle2: 'Dompet Digital',
        tab1SubText2: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
        tab1SubTitle3: 'Pembayaran Melalui Toko',
        tab1SubText3: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
        tab1SubTitle4: 'Qris',
        tab1SubText4: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
        tab1SubTitle5: 'Kartu Kredit',
        tab1SubText5: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
        tab1SubTitle6: 'Pay Later',
        tab1SubText6: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
    
        tab2Title1: 'Transfer secara otomatis dan real-time, bahkan di hari libur',
        tab2Text1: 'Kami memahami pentingnya transfer uang tepat waktu dan bebas dari kesalahan untuk bisnis Anda. Tuntaz telah membangun integrasi langsung dengan berbagai bank untuk menawarkan pengiriman dana dengan kecepatan dan tingkat keberhasilan yang tinggi. Gunakan API kami, nikmati sistem pembayaran yang serba otomatis, dan kembangkan bisnis Anda.',
        tab2Title2: 'Tingkatkan operasional pembayaran Anda dengan pembayaran massa',
        tab2Text2: 'Baik untuk startup atau perusahaan besar, cara transfer uang kami memungkinkan perusahaan Anda berkembang tanpa harus khawatir tentang bagaimana membayar orang lain tepat waktu. Dengan layanan transfer uang kami, Anda dapat mengirim ribuan pembayaran dalam satu hari. Ucapkan selamat tinggal pada sistem payroll yang rumit.',
        tab2SubTitle1: 'Bank',
        tab2SubText1: 'Kami memiliki koneksi ke berbagai bank sehingga Anda dapat melakukan transfer uang ke lebih dari 140 bank lokal di Indonesia. Lihat daftar bank destinasi pengiriman atau dapatkan daftar lengkapnya melalui API.',
        tab2SubTitle2: 'Virtual Akun',
        tab2SubText2: 'Kami dapat membantu transfer uang ke Virtual Account bank-bank termuka di Indonesian termasuk BRI, BNI, Mandiri, CIMB Niaga, Permata, BTN dan NOBU Bank. Limit pengiriman uang tergantung pada limit setiap bank.',
        tab2SubTitle3: 'Dompet Digital',
        tab2SubText3: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
        tab2SubTitle4: 'Bank',
        tab2SubText4: 'Kami memiliki koneksi ke berbagai bank sehingga Anda dapat melakukan transfer uang ke lebih dari 140 bank lokal di Indonesia. Lihat daftar bank destinasi pengiriman atau dapatkan daftar lengkapnya melalui API.',
        tab2SubTitle5: 'Virtual Akun',
        tab2SubText5: 'Kami dapat membantu transfer uang ke Virtual Account bank-bank termuka di Indonesian termasuk BRI, BNI, Mandiri, CIMB Niaga, Permata, BTN dan NOBU Bank. Limit pengiriman uang tergantung pada limit setiap bank.',
        tab2SubTitle6: 'Dompet Digital',
        tab2SubText6: 'Pembayaran dari berbagai bank dapat dikenali dan diterima secara otomatis dan mudah hanya dengan satu Virtual Account dari Xendit, tanpa harus menggunakan rekening dari berbagai bank.',
    
        tab3Title1: 'Terima Pembayaran dengan Mudah dan Nyaman',
        tab3Text1: 'Terima pembayaran secara mudah, kirim invoice dengan membagikan payment link unik kepada pelanggan Anda tanpa perlu melakukan coding. Gunakan UI yang telah tersedia atau desain milik Anda sendiri, atur termin pembayaran, beri pengingat otomatis untuk pelanggan Anda, dan deteksi pembayaran secara instan. Invoice tersedia untuk pembayaran satu kali maupun berulang.',
        tab3Text2: 'Invoice tidak memiliki biaya yang mengikat – bayar sesuai penggunaan. Bahkan, pelanggan Anda dapat melakukan pembayaran melalui transfer bank, kartu kredit dan debit, e-wallet atau secara tunai melalui toko ritel seperti Alfamart atau Indomaret yang tersebar di seluruh Indonesia.',

    },
    EN: {
        textHome1 : "Receive and send payments easily",
        textHome2 : "Tuntaz is a payment gateway that helps your business grow. We help businesses accept multiple payment methods and send funds to multiple destinations, so you can focus on growing your business.",
        acceptPayment: 'Accept Payment',
        disbursment: 'Disbursment',
        paymentLink: 'Payment link',
        benefitTitle: 'Your benefit',
        benefit1Title: 'Efficient business operations',
        benefit1Text: 'Monitor and manage transactions from our dashboard which can be accessed from multiple devices at once and generate reports easily.',
        benefit2Title: 'Notifications in real time',
        benefit2Text: 'Recognize, analyze and receive payments in real time and automatically.',
        benefit3Title: 'Reporting and analytics',
        benefit3Text: 'Use our web-based dashboard to access and download highly detailed financial reports, down to line from the reconciliation of all transactions for transparency.',

        tab1Title1: 'Compatible with various payment methods',
        tab1Text1: 'Expand your business coverage throughout Indonesia and Southeast Asia with our extensive network and partnerships with more than 140 local banks. Receive instant notifications when payments are successful. Make easy reconciliation and refund via Xendit dashboard.',
        tab1SubTitle1: 'Virtual Account',
        tab1SubText1: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        tab1SubTitle2: 'E Wallet',
        tab1SubText2: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        tab1SubTitle3: 'Convinance Store',
        tab1SubText3: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        tab1SubTitle4: 'Qris',
        tab1SubText4: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        tab1SubTitle5: 'Credit Card',
        tab1SubText5: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        tab1SubTitle6: 'Pay Later',
        tab1SubText6: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        
        tab2Title1: 'Transfers are automatic and real-time, even on holidays',
        tab2Text1: 'We understand the importance of timely and error-free money transfers for your business. Tuntaz has built direct integrations with various banks to offer fast fund transfers and high success rates. Use our API, enjoy a fully automated payment system, and grow your business.',
        tab2Title2: 'Improve your payment operations with mass payments',
        tab2Text2: 'Whether for startups or large corporations, our way of transferring money allows your company to grow without having to worry about how to pay others on time. With our money transfer service, you can send thousands of payments in one day. Say goodbye to complicated payroll systems.',
        tab2SubTitle1: 'Bank',
        tab2SubText1: 'We have connections to various banks so you can transfer money to more than 140 local banks in Indonesia. View the list of bank delivery destinations or get the full list via the API.',
        tab2SubTitle2: 'Virtual Account',
        tab2SubText2: 'We can help transfer money to Virtual Accounts of leading banks in Indonesia including BRI, BNI, Mandiri, CIMB Niaga, Permata, BTN and NOBU Bank. The limit for sending money depends on the limit of each bank.',
        tab2SubTitle3: 'E Wallet',
        tab2SubText3: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',
        tab2SubTitle4: 'Bank',
        tab2SubText4: 'We have connections to various banks so you can transfer money to more than 140 local banks in Indonesia. View the list of bank delivery destinations or get the full list via the API.',
        tab2SubTitle5: 'Virtual Account',
        tab2SubText5: 'We can help transfer money to Virtual Accounts of leading banks in Indonesia including BRI, BNI, Mandiri, CIMB Niaga, Permata, BTN and NOBU Bank. The limit for sending money depends on the limit of each bank.',
        tab2SubTitle6: 'E Wallet',
        tab2SubText6: 'Payments from various banks can be recognized and received automatically and easily with just one Virtual Account from Xendit, without having to use accounts from multiple banks.',

        tab3Title1: 'Accept Payment Easily and Conveniently',
        tab3Text1: 'Receive payments easily, send invoices by sharing a unique payment link with your customers without the need for coding. Use predefined UIs or design your own, set payment terms, set automatic reminders for your customers, and detect payments instantly. Invoices are available for one-time or recurring payments.',
        tab3Text2: 'Invoices have no binding fees – pay as you go. In fact, your customers can make payments via bank transfers, credit and debit cards, e-wallets or in cash through retail stores such as Alfamart or Indomaret which are spread throughout Indonesia.',

    }
}